import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';
import { Settings } from '../settings';

@Injectable({
  providedIn: 'root'
})

// Offers methods to contact the backend and perform tasks relating to the data generated by simulation deploys
export class SimulationDeployDataService {

  url = Settings.backendURL + "/api/simulationdeploydata/";

  constructor(private http: HttpClient) {
  }

  // Gets the latest bookmark data generated by a deployed simulation
  getLatestBookmarks(deployName: string, cursor: number): Observable<any> {
    return this.http.get(this.url + "getlatestbookmarks/" + deployName + "/" + cursor.toString());
  }

  // Gets the latest keystroke data generated by a deployed simulation
  getLatestKeystrokes(deployName: string, cursor: number): Observable<any> {
    return this.http.get(this.url + "getlatestkeystrokes/" + deployName + "/" + cursor.toString());
  }

  // Gets the latest query data generated by a deployed simulation
  getLatestQueries(deployName: string, cursor: number): Observable<any> {
    return this.http.get(this.url + "getlatestqueries/" + deployName + "/" + cursor.toString());
  }

  // Gets the latest visited links data generated by a deployed simulation
  getLatestVisitedlinks(deployName: string, cursor: number): Observable<any> {
    return this.http.get(this.url + "getlatestvisitedlinks/" + deployName + "/" + cursor.toString());
  }
  
}